\+DatabaseType Unicode lexical file
\ver 5.0
\desc Nkonya Unicode lexical file
\+mkrset 
\lngDefault NkonyaU
\mkrRecord le

\+mkr a
\nam *
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr af
\nam Alternate form of le
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr al
\nam alternate list
\desc Name alternate list the word is
\lng DefaultU
\rngset Consonant Noun_Class Swadesh Vowel 
\mkrOverThis le
\-mkr

\+mkr an
\nam alternate number
\desc number in the alternate list
\lng DefaultU
\mkrOverThis le
\-mkr

\+mkr anth
\nam anthropological note
\lng DefaultU
\mkrOverThis le
\-mkr

\+mkr awl
\nam *
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr b%
\nam borrowing language
\lng DefaultU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr be
\nam Borrow English
\lng DefaultU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr bh
\nam Borrow Hausa
\lng NkonyaU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr bo
\nam Borrow Ewe
\lng NkonyaU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr bt
\nam Borrowed Twi
\lng NkonyaU
\+fnt 
\Name Ghana Doulos
\Size 12
\rgbColor 0,0,0
\-fnt
\mkrOverThis le
\-mkr

\+mkr com
\nam comment
\lng NkonyaU
\+fnt 
\Name Ghana Doulos
\Size 11
\rgbColor 0,0,0
\-fnt
\mkrOverThis le
\-mkr

\+mkr def
\nam definition
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr dt
\nam date
\lng DefaultU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr gl
\nam gloss
\lng NkonyaU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr grm
\nam grammatical note
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr hlp
\nam need help
\lng NkonyaU
\+fnt 
\Name Ghana Doulos
\Size 11
\rgbColor 0,0,0
\-fnt
\mkrOverThis le
\-mkr

\+mkr idf
\nam free translation of sample
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr idm
\nam example
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr ids
\nam example (South)
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr idt
\nam example translation
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr kinds
\nam subtypes
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr lc
\nam citation form
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr lct
\nam citation form tone
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr le
\nam lexical entry
\lng NkonyaU
\NoWordWrap
\-mkr

\+mkr lt
\nam tone
\lng NkonyaU
\+fnt 
\Name Ghana Doulos
\Size 11
\rgbColor 0,0,0
\-fnt
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr mp
\nam morph property
\desc a morpheme property for CARLA parsing
\lng DefaultU
\mkrOverThis le
\-mkr

\+mkr nn
\nam Northern dialect form
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr pf
\nam parsing form
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr phn
\nam phonetic
\desc Phonetic script form of head
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr pl
\nam plural
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr ps
\nam part of speech
\lng DefaultU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr pt
\nam phonetic tone
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr ptn
\nam plural tone
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr ref
\nam reference
\lng NkonyaU
\+fnt 
\Name Ghana Doulos
\Size 11
\rgbColor 0,0,0
\-fnt
\mkrOverThis le
\-mkr

\+mkr rf
\nam *
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr rph
\nam related phrase
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr rphs
\nam related phrase (South)
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr rpht
\nam related phrase translation
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr rw
\nam related word
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr rws
\nam related word (South)
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr rwt
\nam related translation
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr se
\nam sub entry
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr sem
\nam Proverb
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr sn
\nam Southern dialect form
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr snt
\nam Southern tone
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr stn
\nam Stewart List number
\lng DefaultU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr svb
\nam serial verb
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr svbt
\nam serial verb translation
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr tf
\nam tone frame
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr ths
\nam thesaurus
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr tp
\nam tape number
\lng DefaultU
\NoWordWrap
\mkrOverThis le
\-mkr

\+mkr ul
\nam underlying parsed form
\lng NkonyaU
\mkrOverThis le
\-mkr

\+mkr wv
\nam wave file name
\lng DefaultU
\mkrOverThis le
\-mkr

\-mkrset

\iInterlinCharWd 8
\+filset 

\+fil CC
\mkr le
\txt [cons][cons]
\match_char c
\-fil

\+fil Cr
\mkr le
\txt [cons]r
\match_char c
\-fil

\+fil Nizer
\mkr ps
\txt Nizer
\match_char c
\-fil

\+fil VwV
\mkr le
\txt [vowel]w[vowel]
\match_char c
\-fil

\+fil VyV
\mkr le
\txt [vowel]y[vowel]
\match_char c
\-fil

\+fil a
\mkr mp
\match_char c
\-fil

\+fil borrow twi
\mkr bt
\match_char c
\-fil

\+fil date
\mkr dt
\rel >
\dat 01/Sep/2002
\match_char c
\-fil

\+fil final n
\mkr le
\txt n[#]
\match_char c
\-fil

\+fil idm
\mkr idm
\match_char c
\-fil

\+fil morpheme property
\mkr mp
\match_char c
\-fil

\+fil nouns
\mkr ps
\txt n
\MatchWhole
\match_char c
\-fil

\+fil nouns CVC
\mkr ps
\txt n
\fel And
\mkr le
\txt [#][vowel][cons]
\match_char c
\-fil

\+fil pf
\mkr pf
\match_char c
\-fil

\+fil stewart
\mkr stn
\match_char c
\-fil

\+fil stewart&tape
\mkr stn
\fel And
\mkr tp
\match_char c
\-fil

\+fil two vowel
\mkr le
\txt [vowel][vowel]
\match_char c
\-fil

\+fil verbs
\mkr ps
\txt [#]v
\match_char c
\-fil

\+fil vowel list
\mkr al
\txt Vowel
\match_char c
\-fil

\+fil ya
\mkr idm
\txt [#]ya[#]
\match_char c
\-fil

\-filset

\+jmpset 
\+jmp default
\+drflst 
\-drflst
\-jmp
\-jmpset

\+template 
\fld \gl
\fld \lt
\fld \def
\fld \ps
\fld \tf
\fld \idm
\fld \idt
\fld \dt
\-template
\mkrRecord le
\mkrDateStamp dt
\mkrMultipleMatchShow gl
\+PrintProperties 
\header File: &f, Date: &d
\footer Page &p
\topmargin 1.00 in
\leftmargin 0.25 in
\bottommargin 1.00 in
\rightmargin 0.25 in
\breakrecordswithspace
\recordsspace 100
\-PrintProperties
\+expset 

\+expSF Just le entries
\exportedFile .\2VOWEL.DB
\+mkrsubsetIncluded 
\mkr gl
\mkr le
\-mkrsubsetIncluded
\-expSF

\+expRTF Rich Text Format
\exportedFile .\2VOWEL.RTF
\+rtfPageSetup 
\paperSize A4
\topMargin 2.54
\bottomMargin 2.54
\leftMargin 3.175
\rightMargin 3.175
\gutter 0
\headerToEdge 1.27
\footerToEdge 1.27
\columns 1
\columnSpacing 1.27
\-rtfPageSetup
\-expRTF

\+expSF Standard Format
\exportedFile .\2cons.db
\+mkrsubsetIncluded 
\mkr gl
\mkr le
\-mkrsubsetIncluded
\-expSF

\+expSF idm-idt
\exportedFile .\examples.sfm
\+mkrsubsetIncluded 
\mkr gl
\mkr idm
\mkr ids
\mkr idt
\mkr le
\-mkrsubsetIncluded
\-expSF

\+expSF plural
\exportedFile .\nouns.db
\+mkrsubsetIncluded 
\mkr le
\mkr pl
\-mkrsubsetIncluded
\-expSF

\expDefault plural
\CurrentWindow
\AutoOpen
\SkipProperties
\-expset
\-DatabaseType
